/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AuthedUserRouteImport } from './routes/_authed/user'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedPatientsPatientIdRouteImport } from './routes/_authed/patients/$patientId'
import { Route as AuthedPatientsPatientIdIndexRouteImport } from './routes/_authed/patients/$patientId/index'
import { Route as AuthedPatientsPatientIdSettingsRouteImport } from './routes/_authed/patients/$patientId/settings'
import { Route as AuthedPatientsPatientIdHistoryRouteImport } from './routes/_authed/patients/$patientId/history'
import { Route as AuthedPatientsPatientIdExportRouteImport } from './routes/_authed/patients/$patientId/export'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUserRoute = AuthedUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPatientsPatientIdRoute = AuthedPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPatientsPatientIdIndexRoute =
  AuthedPatientsPatientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)
const AuthedPatientsPatientIdSettingsRoute =
  AuthedPatientsPatientIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)
const AuthedPatientsPatientIdHistoryRoute =
  AuthedPatientsPatientIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)
const AuthedPatientsPatientIdExportRoute =
  AuthedPatientsPatientIdExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/user': typeof AuthedUserRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/patients/$patientId': typeof AuthedPatientsPatientIdRouteWithChildren
  '/patients/$patientId/export': typeof AuthedPatientsPatientIdExportRoute
  '/patients/$patientId/history': typeof AuthedPatientsPatientIdHistoryRoute
  '/patients/$patientId/settings': typeof AuthedPatientsPatientIdSettingsRoute
  '/patients/$patientId/': typeof AuthedPatientsPatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/user': typeof AuthedUserRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/patients/$patientId/export': typeof AuthedPatientsPatientIdExportRoute
  '/patients/$patientId/history': typeof AuthedPatientsPatientIdHistoryRoute
  '/patients/$patientId/settings': typeof AuthedPatientsPatientIdSettingsRoute
  '/patients/$patientId': typeof AuthedPatientsPatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/user': typeof AuthedUserRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/_authed/patients/$patientId': typeof AuthedPatientsPatientIdRouteWithChildren
  '/_authed/patients/$patientId/export': typeof AuthedPatientsPatientIdExportRoute
  '/_authed/patients/$patientId/history': typeof AuthedPatientsPatientIdHistoryRoute
  '/_authed/patients/$patientId/settings': typeof AuthedPatientsPatientIdSettingsRoute
  '/_authed/patients/$patientId/': typeof AuthedPatientsPatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/user'
    | '/sign-in/$'
    | '/patients/$patientId'
    | '/patients/$patientId/export'
    | '/patients/$patientId/history'
    | '/patients/$patientId/settings'
    | '/patients/$patientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/user'
    | '/sign-in/$'
    | '/patients/$patientId/export'
    | '/patients/$patientId/history'
    | '/patients/$patientId/settings'
    | '/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/dashboard'
    | '/_authed/user'
    | '/sign-in/$'
    | '/_authed/patients/$patientId'
    | '/_authed/patients/$patientId/export'
    | '/_authed/patients/$patientId/history'
    | '/_authed/patients/$patientId/settings'
    | '/_authed/patients/$patientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/user': {
      id: '/_authed/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthedUserRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/patients/$patientId': {
      id: '/_authed/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthedPatientsPatientIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/patients/$patientId/': {
      id: '/_authed/patients/$patientId/'
      path: '/'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof AuthedPatientsPatientIdIndexRouteImport
      parentRoute: typeof AuthedPatientsPatientIdRoute
    }
    '/_authed/patients/$patientId/settings': {
      id: '/_authed/patients/$patientId/settings'
      path: '/settings'
      fullPath: '/patients/$patientId/settings'
      preLoaderRoute: typeof AuthedPatientsPatientIdSettingsRouteImport
      parentRoute: typeof AuthedPatientsPatientIdRoute
    }
    '/_authed/patients/$patientId/history': {
      id: '/_authed/patients/$patientId/history'
      path: '/history'
      fullPath: '/patients/$patientId/history'
      preLoaderRoute: typeof AuthedPatientsPatientIdHistoryRouteImport
      parentRoute: typeof AuthedPatientsPatientIdRoute
    }
    '/_authed/patients/$patientId/export': {
      id: '/_authed/patients/$patientId/export'
      path: '/export'
      fullPath: '/patients/$patientId/export'
      preLoaderRoute: typeof AuthedPatientsPatientIdExportRouteImport
      parentRoute: typeof AuthedPatientsPatientIdRoute
    }
  }
}

interface AuthedPatientsPatientIdRouteChildren {
  AuthedPatientsPatientIdExportRoute: typeof AuthedPatientsPatientIdExportRoute
  AuthedPatientsPatientIdHistoryRoute: typeof AuthedPatientsPatientIdHistoryRoute
  AuthedPatientsPatientIdSettingsRoute: typeof AuthedPatientsPatientIdSettingsRoute
  AuthedPatientsPatientIdIndexRoute: typeof AuthedPatientsPatientIdIndexRoute
}

const AuthedPatientsPatientIdRouteChildren: AuthedPatientsPatientIdRouteChildren =
  {
    AuthedPatientsPatientIdExportRoute: AuthedPatientsPatientIdExportRoute,
    AuthedPatientsPatientIdHistoryRoute: AuthedPatientsPatientIdHistoryRoute,
    AuthedPatientsPatientIdSettingsRoute: AuthedPatientsPatientIdSettingsRoute,
    AuthedPatientsPatientIdIndexRoute: AuthedPatientsPatientIdIndexRoute,
  }

const AuthedPatientsPatientIdRouteWithChildren =
  AuthedPatientsPatientIdRoute._addFileChildren(
    AuthedPatientsPatientIdRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedUserRoute: typeof AuthedUserRoute
  AuthedPatientsPatientIdRoute: typeof AuthedPatientsPatientIdRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedUserRoute: AuthedUserRoute,
  AuthedPatientsPatientIdRoute: AuthedPatientsPatientIdRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
