/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as CompareMedisafeRouteImport } from './routes/compare.medisafe'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthedDashboardUserRouteImport } from './routes/_authed/dashboard/user'
import { Route as AuthedDashboardPatientsPatientIdRouteImport } from './routes/_authed/dashboard/patients/$patientId'
import { Route as AuthedDashboardPatientsPatientIdIndexRouteImport } from './routes/_authed/dashboard/patients/$patientId/index'
import { Route as AuthedDashboardPatientsPatientIdSettingsRouteImport } from './routes/_authed/dashboard/patients/$patientId/settings'
import { Route as AuthedDashboardPatientsPatientIdHistoryRouteImport } from './routes/_authed/dashboard/patients/$patientId/history'
import { Route as AuthedDashboardPatientsPatientIdExportRouteImport } from './routes/_authed/dashboard/patients/$patientId/export'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareMedisafeRoute = CompareMedisafeRouteImport.update({
  id: '/compare/medisafe',
  path: '/compare/medisafe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardUserRoute = AuthedDashboardUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const AuthedDashboardPatientsPatientIdRoute =
  AuthedDashboardPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardPatientsPatientIdIndexRoute =
  AuthedDashboardPatientsPatientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDashboardPatientsPatientIdRoute,
  } as any)
const AuthedDashboardPatientsPatientIdSettingsRoute =
  AuthedDashboardPatientsPatientIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedDashboardPatientsPatientIdRoute,
  } as any)
const AuthedDashboardPatientsPatientIdHistoryRoute =
  AuthedDashboardPatientsPatientIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthedDashboardPatientsPatientIdRoute,
  } as any)
const AuthedDashboardPatientsPatientIdExportRoute =
  AuthedDashboardPatientsPatientIdExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AuthedDashboardPatientsPatientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRouteWithChildren
  '/compare/medisafe': typeof CompareMedisafeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/dashboard/user': typeof AuthedDashboardUserRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/dashboard/patients/$patientId': typeof AuthedDashboardPatientsPatientIdRouteWithChildren
  '/dashboard/patients/$patientId/export': typeof AuthedDashboardPatientsPatientIdExportRoute
  '/dashboard/patients/$patientId/history': typeof AuthedDashboardPatientsPatientIdHistoryRoute
  '/dashboard/patients/$patientId/settings': typeof AuthedDashboardPatientsPatientIdSettingsRoute
  '/dashboard/patients/$patientId/': typeof AuthedDashboardPatientsPatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare/medisafe': typeof CompareMedisafeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/dashboard/user': typeof AuthedDashboardUserRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/patients/$patientId/export': typeof AuthedDashboardPatientsPatientIdExportRoute
  '/dashboard/patients/$patientId/history': typeof AuthedDashboardPatientsPatientIdHistoryRoute
  '/dashboard/patients/$patientId/settings': typeof AuthedDashboardPatientsPatientIdSettingsRoute
  '/dashboard/patients/$patientId': typeof AuthedDashboardPatientsPatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRouteWithChildren
  '/compare/medisafe': typeof CompareMedisafeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/_authed/dashboard/user': typeof AuthedDashboardUserRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/patients/$patientId': typeof AuthedDashboardPatientsPatientIdRouteWithChildren
  '/_authed/dashboard/patients/$patientId/export': typeof AuthedDashboardPatientsPatientIdExportRoute
  '/_authed/dashboard/patients/$patientId/history': typeof AuthedDashboardPatientsPatientIdHistoryRoute
  '/_authed/dashboard/patients/$patientId/settings': typeof AuthedDashboardPatientsPatientIdSettingsRoute
  '/_authed/dashboard/patients/$patientId/': typeof AuthedDashboardPatientsPatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/compare/medisafe'
    | '/sign-in/$'
    | '/dashboard/user'
    | '/dashboard/'
    | '/dashboard/patients/$patientId'
    | '/dashboard/patients/$patientId/export'
    | '/dashboard/patients/$patientId/history'
    | '/dashboard/patients/$patientId/settings'
    | '/dashboard/patients/$patientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare/medisafe'
    | '/sign-in/$'
    | '/dashboard/user'
    | '/dashboard'
    | '/dashboard/patients/$patientId/export'
    | '/dashboard/patients/$patientId/history'
    | '/dashboard/patients/$patientId/settings'
    | '/dashboard/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/dashboard'
    | '/compare/medisafe'
    | '/sign-in/$'
    | '/_authed/dashboard/user'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/patients/$patientId'
    | '/_authed/dashboard/patients/$patientId/export'
    | '/_authed/dashboard/patients/$patientId/history'
    | '/_authed/dashboard/patients/$patientId/settings'
    | '/_authed/dashboard/patients/$patientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  CompareMedisafeRoute: typeof CompareMedisafeRoute
  SignInSplatRoute: typeof SignInSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/medisafe': {
      id: '/compare/medisafe'
      path: '/compare/medisafe'
      fullPath: '/compare/medisafe'
      preLoaderRoute: typeof CompareMedisafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/user': {
      id: '/_authed/dashboard/user'
      path: '/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof AuthedDashboardUserRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/patients/$patientId': {
      id: '/_authed/dashboard/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/dashboard/patients/$patientId'
      preLoaderRoute: typeof AuthedDashboardPatientsPatientIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/patients/$patientId/': {
      id: '/_authed/dashboard/patients/$patientId/'
      path: '/'
      fullPath: '/dashboard/patients/$patientId/'
      preLoaderRoute: typeof AuthedDashboardPatientsPatientIdIndexRouteImport
      parentRoute: typeof AuthedDashboardPatientsPatientIdRoute
    }
    '/_authed/dashboard/patients/$patientId/settings': {
      id: '/_authed/dashboard/patients/$patientId/settings'
      path: '/settings'
      fullPath: '/dashboard/patients/$patientId/settings'
      preLoaderRoute: typeof AuthedDashboardPatientsPatientIdSettingsRouteImport
      parentRoute: typeof AuthedDashboardPatientsPatientIdRoute
    }
    '/_authed/dashboard/patients/$patientId/history': {
      id: '/_authed/dashboard/patients/$patientId/history'
      path: '/history'
      fullPath: '/dashboard/patients/$patientId/history'
      preLoaderRoute: typeof AuthedDashboardPatientsPatientIdHistoryRouteImport
      parentRoute: typeof AuthedDashboardPatientsPatientIdRoute
    }
    '/_authed/dashboard/patients/$patientId/export': {
      id: '/_authed/dashboard/patients/$patientId/export'
      path: '/export'
      fullPath: '/dashboard/patients/$patientId/export'
      preLoaderRoute: typeof AuthedDashboardPatientsPatientIdExportRouteImport
      parentRoute: typeof AuthedDashboardPatientsPatientIdRoute
    }
  }
}

interface AuthedDashboardPatientsPatientIdRouteChildren {
  AuthedDashboardPatientsPatientIdExportRoute: typeof AuthedDashboardPatientsPatientIdExportRoute
  AuthedDashboardPatientsPatientIdHistoryRoute: typeof AuthedDashboardPatientsPatientIdHistoryRoute
  AuthedDashboardPatientsPatientIdSettingsRoute: typeof AuthedDashboardPatientsPatientIdSettingsRoute
  AuthedDashboardPatientsPatientIdIndexRoute: typeof AuthedDashboardPatientsPatientIdIndexRoute
}

const AuthedDashboardPatientsPatientIdRouteChildren: AuthedDashboardPatientsPatientIdRouteChildren =
  {
    AuthedDashboardPatientsPatientIdExportRoute:
      AuthedDashboardPatientsPatientIdExportRoute,
    AuthedDashboardPatientsPatientIdHistoryRoute:
      AuthedDashboardPatientsPatientIdHistoryRoute,
    AuthedDashboardPatientsPatientIdSettingsRoute:
      AuthedDashboardPatientsPatientIdSettingsRoute,
    AuthedDashboardPatientsPatientIdIndexRoute:
      AuthedDashboardPatientsPatientIdIndexRoute,
  }

const AuthedDashboardPatientsPatientIdRouteWithChildren =
  AuthedDashboardPatientsPatientIdRoute._addFileChildren(
    AuthedDashboardPatientsPatientIdRouteChildren,
  )

interface AuthedDashboardRouteChildren {
  AuthedDashboardUserRoute: typeof AuthedDashboardUserRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardPatientsPatientIdRoute: typeof AuthedDashboardPatientsPatientIdRouteWithChildren
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardUserRoute: AuthedDashboardUserRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardPatientsPatientIdRoute:
    AuthedDashboardPatientsPatientIdRouteWithChildren,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  CompareMedisafeRoute: CompareMedisafeRoute,
  SignInSplatRoute: SignInSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
